export default {
  homePageTitleText:
    'interactive investor – the UK’s number one flat-fee investment platform',
  homePageUrl: 'https://www.ii.co.uk/',
  servicesTextArray: [
    'Trading Account',
    'Stocks and Shares ISA',
    'SIPP',
    'Junior ISA',
    'See all ii Accounts',
    'Our Charges',
    'Investing with ii',
    'Transferring to ii',
    'International Investing',
    'Regular Investing',
    'Live Pricing',
    'IPOs',
    'Ethical Investing',
    'Refer a friend',
  ],
  servicesLinksArray: [
    'https://www.ii.co.uk/ii-accounts/trading-account',
    'https://www.ii.co.uk/ii-accounts/isa',
    'https://www.ii.co.uk/ii-accounts/sipp',
    'https://www.ii.co.uk/ii-accounts/isa/junior-isa',
    'https://www.ii.co.uk/ii-accounts',
    'https://www.ii.co.uk/our-charges',
    'https://www.ii.co.uk/investing-with-ii',
    'https://www.ii.co.uk/investing-with-ii/transferring-to-ii',
    'https://www.ii.co.uk/investing-with-ii/international-investing',
    'https://www.ii.co.uk/investing-with-ii/regular-investing',
    'https://www.ii.co.uk/live-pricing',
    'https://www.ii.co.uk/ipos',
    'https://www.ii.co.uk/ethical-investing',
    'https://www.ii.co.uk/ii-for-friends/customer',
  ],
};
